### ISSUE TITLE
Not compatible with Flickity v1

### ISSUE THREAD

**Issue by hschaefer123** [metafizzy/flickity-bg-lazyload#1]
Hi Desandro,
i was not able to run the bg lazyload with flickity!

After switching event select to cellSelect

``` javascript
// Flickity background lazyload v1.0.0

proto._createBgLazyLoad = function() {
  //this.on('select', this.bgLazyLoad); // does not work for me
  this.on('cellSelect', this.bgLazyLoad);
};
```

the code works as expected!

Can you confirm, that i am using the code right?

BTW: Will this feature be part of flickity 2.x and when will you release the upcomming version?

Thanks for the great library pieces.

Regards Holger

**Comment by desandro** [comment]
bgLazyLoad is designed to work with Flickity v2, not v1 — although you can hack it to work. Flickity v2 will be released next week. You caught a sneak peak of what's to come 😉
