### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createMethods' of undefined

### ISSUE THREAD

**Issue by jserrao** [metafizzy/flickity-bg-lazyload#4]
Dave:

Getting a weird error here, thought you might have some insights. Whenever I include the `flickity-bg-lazyload` package via Bower, I get this error in the console:
`Uncaught TypeError: Cannot read property 'createMethods' of undefined`

Thumbed through a lot of documentation and found a similar type of issue in the Masonry repo:
https://github.com/desandro/masonry/issues/618

Interestingly, the comment towards the bottom [https://github.com/desandro/masonry/issues/618#issuecomment-136295697] deals with a similar stack to what I'm building on: WordPress with the Roots / Sage ecosystem. I tried her workaround with no avail.

Here is my bower.json file:

```
{
  "name": "sage",
  "homepage": "https://roots.io/sage/",
  "authors": [
    "Ben Word <ben@benword.com>"
  ],
  "license": "MIT",
  "private": true,
  "dependencies": {
    "bootstrap-sass": "3.3.6",
    "flickity": "^2.0.0",
    "flickity-bg-lazyload": "^1.0.0",
    "jquery.lazyload": "^1.9.7",
    "waypoints": "^4.0.1"
  },
  "overrides": {
    "flickity-bg-lazyload": {
      "main": ["./dist/scripts/flickity-bg-lazyload.js"]
    },
    "bootstrap-sass": {
      "main": [
        "./assets/stylesheets/_bootstrap.scss",
        "./assets/javascripts/bootstrap/transition.js",
        "./assets/javascripts/bootstrap/button.js",
        "./assets/javascripts/bootstrap/collapse.js",
        "./assets/javascripts/bootstrap/modal.js",
        "./assets/javascripts/bootstrap/tab.js"
      ]
    }
  }
}
```

Also, this is how my scripts load on the page, which seems ok to me:

```
<script type="text/javascript" src="//localhost:3000/wp-includes/js/jquery/suggest.min.js?ver=1.1-20110113"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/flickity.js"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/flickity-bg-lazyload.js"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/clamp.js"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/jquery-lazyload.js"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/waypoints.js"></script>
<script type="text/javascript" src="//localhost:3000/wp-content/themes/aa-theme/dist/scripts/main.js"></script>
```

Let me know if you have any insight on this one, thanks in advance.

**Comment by desandro** [comment]
Sorry, but I don't have expertise with Roots + Sage. From the Masonry issue, it appears you can try overriding Flickity's dependencies and use `flickity.pkgd.js` instead.

**Comment by dylanfisher** [comment]
Just in case anyone else runs into this issue, make sure you load `flickity.pkgd.js` before `bg-lazyload.js`, or you will get the same error. In my case that meant renaming the scripts so that they were compiled in the correct order. 

`0_flickity.pkgd.min.js`
`1_flickity.bg-lazyload.js`
