### ISSUE TITLE
builtin loading animation svg

### ISSUE THREAD

**Issue by airanode** [metafizzy/flickity-bg-lazyload#5]
Is there any builtin loading animation svg for this?

**Comment by desandro** [comment]
Sorry nope.

**Comment by PaoloFalomo** [comment]
@xemox i know this is quite old but you can achieve that with [native flickity callbacks](https://flickity.metafizzy.co/events.html#select) and use of an svg animator like [Vivus Js](https://maxwellito.github.io/vivus/)
![lug-20-2017 12-24-19](https://user-images.githubusercontent.com/10535089/28413041-71ffc5c2-6d46-11e7-95b1-55145f63b5a8.gif)


See my codepen: https://codepen.io/PaoloFalomo/pen/XgvXvR

**Comment by KonaKoffee00** [comment]
Thanks for the reply. Much appreciated.
Cheers,
Hope
