### ISSUE TITLE
Scroll in front of Flickity (with bg-lazy-load) get lagging

### ISSUE THREAD

**Issue by khoipro** [metafizzy/flickity-bg-lazyload#6]
Issue: http://recordit.co/BmEG7KrcoE

Current options:

```
    var options = {
      cellAlign: 'left',
      pageDots: false,
      contain: true,
      groupCells: true,
      bgLazyLoad: 1
    };
```

When disable *bglazyload* and using default Flickity, it works normally.

Settings: 5 items shown, 30 items in a single carousel.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
